# platform :ios, '9.0'

target 'Log In Test' do

  use_frameworks!

  # Pods for Log In Test
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod "UPCarouselFlowLayout"
  target 'Log In TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Log In TestUITests' do
    # Pods for testing
  end

end
